sequenceDiagram
    actor Biletomat
    participant SystemTransakcyjny

    Biletomat->>SystemTransakcyjny: Przesłanie żądania autoryzacji
    SystemTransakcyjny->>Biletomat: Potwierdzenie autoryzacji
