sequenceDiagram
    actor Użytkownik
    participant Biletomat

    Użytkownik->>Biletomat: Wybór rodzaju biletu
    Biletomat->>Użytkownik: Wyświetlenie dostępnych opcji
    Użytkownik->>Biletomat: Potwierdzenie wyboru
    Biletomat->>Użytkownik: Wydanie biletu
